services:
  - type: web
    name: hivepulse
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: node src/server.js
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: HIVE_INTERNAL_KEY
        value: hive_internal_125e04e071e8829be631ea0216dd4a0c9b707975fcecaf8c62c6a2ab43327d46
      - key: HIVEGATE_URL
        value: https://hivegate.onrender.com
